package bonneice.vista;
import java.awt.Image;
import java.awt.event.KeyEvent;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alex
 */
public class Principal extends javax.swing.JFrame {
    
    //Arreglos
    String[] nombres;
    int[][] helados;
    
    //Modelos para las tablas
    String encabezado1[] = new String[]{"Vendedor", "Sencillo", "Doble","BonIsote","Mega"};
    String encabezado2[] = new String[]{"Sencillo", "Doble","BonIsote","Mega"};
    DefaultTableModel defaultTable1, defaultTable2;

    public Principal() {
        initComponents();
        
        //Para que las tablas no sean editables
        defaultTable1 = new DefaultTableModel(encabezado1,0){
            @Override
            public boolean isCellEditable(int row, int column) {
            //all cells false
            return false;
        }
        };
        
        defaultTable2 = new DefaultTableModel(encabezado2,0){
            @Override
            public boolean isCellEditable(int row, int column) {
            //all cells false
            return false;
        }
        };
        tablaVendedor.setModel(defaultTable1);
        tablaCategoria.setModel(defaultTable2);
        setLocationRelativeTo(null);
        
        //Ajusta el icono del helado al tamaño del Jlabel
        ImageIcon imagen1 = new ImageIcon(getClass().getResource("/bonneice/imagenes/helado.png"));
        ImageIcon imagen2 = new ImageIcon(imagen1.getImage().getScaledInstance(logo.getWidth(), logo.getHeight(), Image.SCALE_DEFAULT));
        logo.setIcon(imagen2);
        
        this.desactivarElementos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        logo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        vendedor = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        totalVendedores = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        sencillo = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        doble = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        bonisote = new javax.swing.JTextField();
        mega = new javax.swing.JTextField();
        jSeparator6 = new javax.swing.JSeparator();
        agregar = new javax.swing.JButton();
        reiniciar = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaVendedor = new javax.swing.JTable();
        actualizar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        limpiar = new javax.swing.JButton();
        informacion = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tablaCategoria = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        logo.setBackground(new java.awt.Color(255, 255, 255));
        logo.setForeground(new java.awt.Color(255, 255, 255));
        logo.setToolTipText("");

        jLabel3.setBackground(new java.awt.Color(0, 204, 204));
        jLabel3.setFont(new java.awt.Font("Ebrima", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Heladería Bonne Ice");

        vendedor.setBackground(new java.awt.Color(0, 102, 102));
        vendedor.setForeground(new java.awt.Color(255, 153, 0));
        vendedor.setBorder(null);
        vendedor.setCaretColor(new java.awt.Color(255, 255, 255));
        vendedor.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        vendedor.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                vendedorFocusGained(evt);
            }
        });
        vendedor.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                vendedorKeyPressed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Vendedor:");

        jLabel5.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Sencillo:");

        jLabel6.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Doble:");

        jLabel7.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("BonIsote:");

        jLabel8.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Mega:");

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        totalVendedores.setToolTipText("Presione \"Enter\" al terminar");
        totalVendedores.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                totalVendedoresKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                totalVendedoresKeyTyped(evt);
            }
        });

        jLabel9.setBackground(new java.awt.Color(0, 0, 0));
        jLabel9.setFont(new java.awt.Font("Ebrima", 0, 14)); // NOI18N
        jLabel9.setText("Total vendedores:");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(totalVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(totalVendedores, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 6, Short.MAX_VALUE))
        );

        sencillo.setBackground(new java.awt.Color(0, 102, 102));
        sencillo.setForeground(new java.awt.Color(255, 153, 0));
        sencillo.setBorder(null);
        sencillo.setCaretColor(new java.awt.Color(255, 255, 255));
        sencillo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                sencilloKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                sencilloKeyTyped(evt);
            }
        });

        doble.setBackground(new java.awt.Color(0, 102, 102));
        doble.setForeground(new java.awt.Color(255, 153, 0));
        doble.setBorder(null);
        doble.setCaretColor(new java.awt.Color(255, 255, 255));
        doble.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                dobleKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                dobleKeyTyped(evt);
            }
        });

        bonisote.setBackground(new java.awt.Color(0, 102, 102));
        bonisote.setForeground(new java.awt.Color(255, 153, 0));
        bonisote.setBorder(null);
        bonisote.setCaretColor(new java.awt.Color(255, 255, 255));
        bonisote.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                bonisoteKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                bonisoteKeyTyped(evt);
            }
        });

        mega.setBackground(new java.awt.Color(0, 102, 102));
        mega.setForeground(new java.awt.Color(255, 153, 0));
        mega.setBorder(null);
        mega.setCaretColor(new java.awt.Color(255, 255, 255));
        mega.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                megaKeyPressed(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                megaKeyTyped(evt);
            }
        });

        agregar.setBackground(new java.awt.Color(0, 102, 102));
        agregar.setForeground(new java.awt.Color(255, 255, 255));
        agregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/agregar1.png"))); // NOI18N
        agregar.setText("Agregar");
        agregar.setBorderPainted(false);
        agregar.setContentAreaFilled(false);
        agregar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        agregar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/agregar1.png"))); // NOI18N
        agregar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/agregar2.png"))); // NOI18N
        agregar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agregarActionPerformed(evt);
            }
        });

        reiniciar.setBackground(new java.awt.Color(0, 102, 102));
        reiniciar.setForeground(new java.awt.Color(255, 255, 255));
        reiniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/reiniciar1.png"))); // NOI18N
        reiniciar.setText("Reiniciar");
        reiniciar.setBorderPainted(false);
        reiniciar.setContentAreaFilled(false);
        reiniciar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        reiniciar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/reiniciar1.png"))); // NOI18N
        reiniciar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/reiniciar2.png"))); // NOI18N
        reiniciar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        reiniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reiniciarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jSeparator6, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(mega, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator5, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(bonisote, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator4, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(doble, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sencillo, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator3, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(vendedor, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jSeparator2, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(agregar)
                                .addGap(18, 18, 18)
                                .addComponent(reiniciar)))))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(logo, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(vendedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(sencillo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(doble, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bonisote, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mega, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator6, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(agregar)
                    .addComponent(reiniciar))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablaVendedor.setBackground(new java.awt.Color(0, 153, 153));
        tablaVendedor.setForeground(new java.awt.Color(255, 255, 255));
        tablaVendedor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tablaVendedor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaVendedorMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tablaVendedor);

        actualizar.setBackground(new java.awt.Color(0, 102, 102));
        actualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/actualizar1.png"))); // NOI18N
        actualizar.setText("Actualizar");
        actualizar.setToolTipText("");
        actualizar.setBorderPainted(false);
        actualizar.setContentAreaFilled(false);
        actualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        actualizar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/actualizar1.png"))); // NOI18N
        actualizar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/actualizar2.png"))); // NOI18N
        actualizar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        actualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel2.setText("Cargas por vendedor");

        limpiar.setBackground(new java.awt.Color(0, 102, 102));
        limpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/limpiar1.png"))); // NOI18N
        limpiar.setText("Limpiar campos");
        limpiar.setToolTipText("");
        limpiar.setBorderPainted(false);
        limpiar.setContentAreaFilled(false);
        limpiar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        limpiar.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/limpiar1.png"))); // NOI18N
        limpiar.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/limpiar2.png"))); // NOI18N
        limpiar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limpiarActionPerformed(evt);
            }
        });

        informacion.setBackground(new java.awt.Color(0, 102, 102));
        informacion.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/info1.png"))); // NOI18N
        informacion.setToolTipText("");
        informacion.setBorderPainted(false);
        informacion.setContentAreaFilled(false);
        informacion.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        informacion.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/info1.png"))); // NOI18N
        informacion.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/bonneice/imagenes/info2.png"))); // NOI18N
        informacion.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        informacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                informacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(actualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(limpiar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(informacion, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(15, 15, 15))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(actualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(limpiar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(informacion))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 377, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        tablaCategoria.setBackground(new java.awt.Color(255, 153, 0));
        tablaCategoria.setForeground(new java.awt.Color(255, 255, 255));
        tablaCategoria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(tablaCategoria);

        jLabel1.setFont(new java.awt.Font("Ebrima", 0, 18)); // NOI18N
        jLabel1.setText("Total de cargas por categoría del producto");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 559, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(116, 116, 116))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    //Funcion que verifica las teclas presionadas y manda un mensaje si no es numero
    public void verificar(KeyEvent evt){
    char caracter = evt.getKeyChar();
        if(Character.isLetter(caracter)){
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(rootPane, "Igrese solo numeros");
        }
    }
    
    //Manda la primera posicion vacía que encuentre
    public int posicionVacia(){
        int posicion = -1;
        for(int i=0; i<nombres.length; i++){
            if(nombres[i]==null){
                posicion = i;
                break;
            }
        }
        return posicion;
    }
    
    //Imprime en las dos tablas
    public void imprimirArreglos(){
        int[] contador = new int[4];
        for(int fila=0; fila<nombres.length; fila++){
            
            if(nombres[fila]!=null){
                Object[] objeto = new Object[5];
                objeto[0] = nombres[fila];
                
                for(int columna=0; columna<helados[fila].length; columna++){
                    objeto[columna+1] = helados[fila][columna];
                    contador[columna] = contador[columna] + helados[fila][columna];
                }
                defaultTable1.addRow(objeto);
            }
        }
        Object[] objeto2 = {contador[0], contador[1], contador[2], contador[3]};
        defaultTable2.addRow(objeto2);
    }
    
    
    //Desactiva ciertos elementos
    public void desactivarElementos(){
        vendedor.setEditable(false);
        sencillo.setEditable(false);
        doble.setEditable(false);
        bonisote.setEditable(false);
        mega.setEditable(false);
        agregar.setEnabled(false);
        actualizar.setEnabled(false);
        limpiar.setEnabled(false);
    }
    
//Activa ciertos elementos
    public void activarElementos(){
        vendedor.setEditable(true);
        sencillo.setEditable(true);
        doble.setEditable(true);
        bonisote.setEditable(true);
        mega.setEditable(true);
        agregar.setEnabled(true);
        limpiar.setEnabled(true);
    }
    
    //Funcion adicional para restablecer elementos
    public void limpiarCampos(){
        vendedor.setText("");
        sencillo.setText("");
        doble.setText("");
        bonisote.setText("");
        mega.setText("");
        vendedor.requestFocus();
        tablaVendedor.clearSelection();
        actualizar.setEnabled(false);
    }
    
    //Insertar el total de vendedor y al presionar enter guardar
    private void totalVendedoresKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalVendedoresKeyPressed
        try{
            if(evt.getKeyCode()== KeyEvent.VK_ENTER){
                int n = Integer.parseInt(totalVendedores.getText());
                nombres = new String[n];
                helados = new int[n][4];  
                totalVendedores.setEnabled(false);
                this.activarElementos();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "Numero no valido");
            totalVendedores.setText("");
        }
    }//GEN-LAST:event_totalVendedoresKeyPressed

    private void totalVendedoresKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_totalVendedoresKeyTyped
        this.verificar(evt);
    }//GEN-LAST:event_totalVendedoresKeyTyped
    
    //Boton agregar
    private void agregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agregarActionPerformed
        if(vendedor.getText().isEmpty() | sencillo.getText().isEmpty() | doble.getText().isEmpty()|
                bonisote.getText().isEmpty() | mega.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane, "No pueden haber campos vacios");
        return;
        }
        int posicion = this.posicionVacia();
        if(posicion != -1){
            try{
                nombres[posicion] = vendedor.getText();
                helados[posicion][0] = Integer.parseInt(sencillo.getText());
                helados[posicion][1] = Integer.parseInt(doble.getText());
                helados[posicion][2] = Integer.parseInt(bonisote.getText());
                helados[posicion][3] = Integer.parseInt(mega.getText());
                defaultTable1.setRowCount(0);
                defaultTable2.setRowCount(0);
                this.imprimirArreglos();
                this.limpiarCampos();
                if(posicion+1==nombres.length){
                    agregar.setEnabled(false);
                }
            }catch(Exception e){
                JOptionPane.showMessageDialog(rootPane, "Error al agregar");
                nombres[posicion] = null;
            }
        }else{
            JOptionPane.showMessageDialog(rootPane, "Limite alcanzado");
        }
        
    }//GEN-LAST:event_agregarActionPerformed
    //Boton reiniciar
    private void reiniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reiniciarActionPerformed
        defaultTable1.setRowCount(0);
        defaultTable2.setRowCount(0);
        totalVendedores.setText("");
        totalVendedores.setEnabled(true);
        totalVendedores.requestFocus();
        vendedor.setText("");
        sencillo.setText("");
        bonisote.setText("");
        mega.setText("");
        doble.setText("");
        nombres=null;
        this.desactivarElementos();
    }//GEN-LAST:event_reiniciarActionPerformed
    
    //Al pulsar un elemento en la tabla de vendedores se pinte en los campos de entrada de datos
    private void tablaVendedorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaVendedorMouseClicked
        int fila = tablaVendedor.getSelectedRow();
        
        vendedor.setText(defaultTable1.getValueAt(fila, 0).toString());
        sencillo.setText(defaultTable1.getValueAt(fila, 1).toString());
        doble.setText(defaultTable1.getValueAt(fila, 2).toString());
        bonisote.setText(defaultTable1.getValueAt(fila, 3).toString());
        mega.setText(defaultTable1.getValueAt(fila, 4).toString());
        agregar.setEnabled(false);
        actualizar.setEnabled(true);
    }//GEN-LAST:event_tablaVendedorMouseClicked
    
    //Boton actualizar
    private void actualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_actualizarActionPerformed
        try{
            int dialogButton = JOptionPane.YES_NO_OPTION;
            int dialogResult = JOptionPane.showConfirmDialog(this, "¿Actualizar este elemento?", "Aceptar", dialogButton);
                
            if(dialogResult==0){
                int fila = tablaVendedor.getSelectedRow();
                nombres[fila] = vendedor.getText();
                helados[fila][0] = Integer.parseInt(sencillo.getText());
                helados[fila][1] = Integer.parseInt(doble.getText());
                helados[fila][2] = Integer.parseInt(bonisote.getText());
                helados[fila][3] = Integer.parseInt(mega.getText());
                defaultTable1.setRowCount(0);
                defaultTable2.setRowCount(0);
                this.imprimirArreglos();
                this.limpiarCampos();
            }
        }catch(Exception e){
            JOptionPane.showMessageDialog(rootPane, "No se pudo actualizar"+e.getMessage());
        }
        this.limpiarCampos();
        tablaVendedor.clearSelection();
        actualizar.setEnabled(false);
    }//GEN-LAST:event_actualizarActionPerformed

    private void limpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limpiarActionPerformed
        this.limpiarCampos();
    }//GEN-LAST:event_limpiarActionPerformed

    private void sencilloKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sencilloKeyTyped
        this.verificar(evt);
    }//GEN-LAST:event_sencilloKeyTyped

    private void dobleKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobleKeyTyped
        this.verificar(evt);
    }//GEN-LAST:event_dobleKeyTyped

    private void bonisoteKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bonisoteKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            mega.requestFocus();
        }
    }//GEN-LAST:event_bonisoteKeyPressed

    private void megaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_megaKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            agregar.doClick();
        }
    }//GEN-LAST:event_megaKeyPressed

    private void vendedorKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_vendedorKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            sencillo.requestFocus();
        }
    }//GEN-LAST:event_vendedorKeyPressed

    private void sencilloKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_sencilloKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            doble.requestFocus();
        }
    }//GEN-LAST:event_sencilloKeyPressed

    private void dobleKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_dobleKeyPressed
        if(evt.getKeyCode()== KeyEvent.VK_ENTER){
            bonisote.requestFocus();
        }
    }//GEN-LAST:event_dobleKeyPressed

    private void bonisoteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_bonisoteKeyTyped
        this.verificar(evt);
    }//GEN-LAST:event_bonisoteKeyTyped

    private void megaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_megaKeyTyped
        this.verificar(evt);
    }//GEN-LAST:event_megaKeyTyped

    private void vendedorFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_vendedorFocusGained
        if(this.posicionVacia()!=-1 & tablaVendedor.getSelectedRow()<0){
            agregar.setEnabled(true);
        }
    }//GEN-LAST:event_vendedorFocusGained
    
    //Boton info
    private void informacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_informacionActionPerformed
       JOptionPane.showMessageDialog(rootPane, "By: Alex Cordova");
    }//GEN-LAST:event_informacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton actualizar;
    private javax.swing.JButton agregar;
    private javax.swing.JTextField bonisote;
    private javax.swing.JTextField doble;
    private javax.swing.JButton informacion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JButton limpiar;
    private javax.swing.JLabel logo;
    private javax.swing.JTextField mega;
    private javax.swing.JButton reiniciar;
    private javax.swing.JTextField sencillo;
    private javax.swing.JTable tablaCategoria;
    private javax.swing.JTable tablaVendedor;
    private javax.swing.JTextField totalVendedores;
    private javax.swing.JTextField vendedor;
    // End of variables declaration//GEN-END:variables
}
